### ISSUE TITLE
Assignment 1 comment

### ISSUE THREAD

**Issue by dmadrigalejos** [benedictfernando/oop#2]
Gumagana ba ito..? bat walang yung ibng files?

**Comment by benedictfernando** [comment]
**_Hello Sir Madrigalejos~ much thanks po for this feedback!_**

Yes po :) All good and working sya~ ininclude ko lang po yung ibang mga feeling ko na di gaanong need na files sa _.gitignore_ para mas makafocus yung directory sa essence nung particular program, and also to save narin po space in the repo. However, I can reupload naman po the codes here at the branches in case you may kindly want to see all the other files.

Anyhow, just let me know lang po in case na need ko pang i-upload those. **_Regardless, thank you so much for these po!_**
